export const Report_Date=[
 {
    id:"1",
    Totalorders:"10",
    Totalcustomers:4,
    Totalearnings:"$5000",
    Totaldelivery:"4",
    Deliverydate:new Date("12/02/2019"),
    Orderreport:"Delivered",
 },
 { id:"3",
    Totalorders:"7",
    Totalcustomers:2,
    Totalearnings:"$900",
    Totaldelivery:"0",
    Deliverydate:new Date("12/09/2020"),
    Orderreport:"Pending",
 },
 { id:"2",
    Totalorders:"24",
    Totalcustomers:12,
    Totalearnings:"$10000",
    Totaldelivery:"23",
    Deliverydate:new Date('08/11/2021'),
    Orderreport:"Delivered",
 },
]